# Generated by Django 4.2.3 on 2023-07-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_game_id_gameplayer_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='created_by_user_id',
            new_name='created_by_user',
        ),
    ]
