# Generated by Django 4.2.3 on 2023-08-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_player_user_alter_player_created_by_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
