# Generated by Django 4.2.3 on 2023-08-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_game_double_last_round_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="double_last_round_points",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
