# Generated by Django 4.2.3 on 2023-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_rename_gameroundplayer_gameroundgameplayer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameround",
            name="total_tricks_predicted",
            field=models.IntegerField(null=True),
        ),
    ]
