# Generated by Django 4.2.3 on 2023-07-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_game_card_number_descending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="winning_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winning_players",
                to="games.player",
            ),
        ),
    ]
