# Generated by Django 4.2.3 on 2023-07-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0010_remove_game_winning_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="winner",
            field=models.BooleanField(default=False),
        ),
    ]
