# Generated by Django 4.2.3 on 2023-07-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_gameplayer_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='winner',
        ),
    ]
